# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slacko < Formula
  desc "A lightweight, keyboard-driven TUI client for Slack"
  homepage "https://github.com/m96-chan/Slacko"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/m96-chan/Slacko/releases/download/v0.2.0/Slacko_0.2.0_darwin_amd64.tar.gz"
      sha256 "97dede279f619e495c3dc98989800f5bd96b5ddf97bc0c7066e3f9ef28d7a290"

      define_method(:install) do
        bin.install "slacko"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/m96-chan/Slacko/releases/download/v0.2.0/Slacko_0.2.0_darwin_arm64.tar.gz"
      sha256 "f88907b670e1b778af8c9c4b8d2aae59bfffaa084992ca7967e911add9a25829"

      define_method(:install) do
        bin.install "slacko"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/m96-chan/Slacko/releases/download/v0.2.0/Slacko_0.2.0_linux_amd64.tar.gz"
      sha256 "06238e1086c1ffb1ee795328236129e23eb6115f896445daa9a2158a51c05274"
      define_method(:install) do
        bin.install "slacko"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/m96-chan/Slacko/releases/download/v0.2.0/Slacko_0.2.0_linux_arm64.tar.gz"
      sha256 "60a3e2066eabe6a95e6d739c9a87d5830a5b5fbc8db010238068e6763c6bdd1c"
      define_method(:install) do
        bin.install "slacko"
      end
    end
  end
end
