# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slacko < Formula
  desc "A lightweight, keyboard-driven TUI client for Slack"
  homepage "https://github.com/m96-chan/Slacko"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/m96-chan/Slacko/releases/download/v0.1.0/Slacko_0.1.0_darwin_amd64.tar.gz"
      sha256 "0913f38bba0a9f912ca7912309f00e98cf53228deda39240aa6ff013437e5457"

      define_method(:install) do
        bin.install "slacko"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/m96-chan/Slacko/releases/download/v0.1.0/Slacko_0.1.0_darwin_arm64.tar.gz"
      sha256 "3b8b60eb33585a33a22830f5078f42cbc0de025eaab44aa25935b19041c19564"

      define_method(:install) do
        bin.install "slacko"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/m96-chan/Slacko/releases/download/v0.1.0/Slacko_0.1.0_linux_amd64.tar.gz"
      sha256 "232e6481a8567d1ebc8f3fa265588c86f0406edb6f120a8a45615a14eea191bd"
      define_method(:install) do
        bin.install "slacko"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/m96-chan/Slacko/releases/download/v0.1.0/Slacko_0.1.0_linux_arm64.tar.gz"
      sha256 "20dbbbbb8050165eaffb3be76773bf3a42cf44f867a074c5e80dafe59f5fddc6"
      define_method(:install) do
        bin.install "slacko"
      end
    end
  end
end
